#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
echo "Refreshing ctags"
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --languages=-javascript,sql --langmap=Lisp:+.clj
mv .git/tags.$$ .git/tags
